#!/usr/bin/env python3
"""Reduce the generated README to its terminal hero and GitHub activity cards."""

from pathlib import Path
import sys

STATS_BASE_URL = "https://github-readme-stats-seven-sigma-13.vercel.app"


def simplify_readme(path: Path) -> None:
    content = path.read_text(encoding="utf-8")
    foreground_heading = "\n## Foreground jobs\n"

    if foreground_heading not in content:
        raise RuntimeError(f"Generated profile sections were not found in {path}")

    introduction = content.split(foreground_heading, maxsplit=1)[0].rstrip()
    if not introduction.endswith("."):
        introduction = f"{introduction}."

    stats_dark = (
        f"{STATS_BASE_URL}/api?username=Kotomiya07&amp;custom_title=Kotomiya07%27s%20GitHub%20Stats&amp;show_icons=true"
        "&amp;include_all_commits=true&amp;hide_border=true"
        "&amp;title_color=58A6FF&amp;text_color=C9D1D9&amp;icon_color=58A6FF&amp;bg_color=0D1117"
    )
    stats_light = (
        f"{STATS_BASE_URL}/api?username=Kotomiya07&amp;custom_title=Kotomiya07%27s%20GitHub%20Stats&amp;show_icons=true"
        "&amp;include_all_commits=true&amp;hide_border=true"
        "&amp;title_color=0969DA&amp;text_color=1F2328&amp;icon_color=0969DA&amp;bg_color=FFFFFF"
    )
    simplified = f"""{introduction}

<p>
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="{stats_dark}">
    <source media="(prefers-color-scheme: light)" srcset="{stats_light}">
    <img alt="Kotomiya07 GitHub statistics" src="{stats_light}" width="450" align="top">
  </picture>
</p>

<!-- Generated by profile-control-plane. Edit profile.yaml and scripts/simplify-readme.py, not this file. -->
"""
    path.write_text(simplified, encoding="utf-8")


def main() -> None:
    readme_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(".profile-output/README.md")
    simplify_readme(readme_path)


if __name__ == "__main__":
    main()
